Repository Mapwize/mapwize-ui-js, pull requests merged in 2019-12, with the labels that each got.

#52 Fix documentation
  README.md
  package-lock.json
  package.json
  src/ui.ts
Labels: dependencies, help wanted

#55 option mainColor: Change border color on focus input
  src/header/directionBar/directionBar.scss
  src/header/directionBar/directionBar.ts
Labels: enhancement

#76 fix display of language and universe selector
  src/footer/venue/venue.ts
Labels: bug
